<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PackageId>Karamem0.BookingsBot.Web</PackageId>
    <Version>0.0.0</Version>
    <Authors>karamem0</Authors>
    <Company>karamem0</Company>
    <Product>BookingsBot</Product>
    <Copyright>Copyright (c) 2021-2025 karamem0</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/karamem0/bookings-bot</PackageProjectUrl>
    <AssemblyVersion>0.0.0</AssemblyVersion>
    <FileVersion>0.0.0</FileVersion>
    <RootNamespace>Karamem0.BookingsBot</RootNamespace>
    <SpaRoot>../../client/</SpaRoot>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <UserSecretsId>12d5f653-5a3c-4261-83af-10204b52130d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveCards.Templating" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Agents.Authentication" />
    <PackageReference Include="Microsoft.Agents.Authentication.Msal" />
    <PackageReference Include="Microsoft.Agents.Builder" />
    <PackageReference Include="Microsoft.Agents.Builder.Dialogs" />
    <PackageReference Include="Microsoft.Agents.Hosting.AspNetCore" />
    <PackageReference Include="Microsoft.Agents.Storage.Blobs" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\StringResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>StringResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\StringResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>StringResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Cards\*.json" />
  </ItemGroup>

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>wwwroot\%(DistFiles.RecursiveDir)%(DistFiles.FileName)%(DistFiles.Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>

</Project>
