name: Trigger on main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build source
    uses: ./.github/workflows/build-source.yml
    secrets: inherit
  deploy:
    name: Deploy to Azure
    needs: build
    uses: ./.github/workflows/deploy-to-azure.yml
    secrets: inherit
