on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  create-release:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repos
        uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
